stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py 
      - data/dataset.csv
    params:
      - data_ingestion.test_size
    outs:
      - data/raw